import type { RuleService } from '@/types'
import { geosite } from '../ruleProviders'

/** US first: most AI services block or degrade HK / CN exits. */
const AI_CANDIDATES = [
  'region:us:auto',
  'region:us:manual',
  'region:jp:auto',
  'region:sg:auto',
  'region:uk:auto',
  'sources:all',
  'global:auto',
  'global:manual',
]

export const aiServices: RuleService[] = [
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    icon: '🤖',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('openai')],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 100,
  },
  {
    id: 'claude',
    label: 'Claude',
    icon: '✳️',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('anthropic')],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 99,
  },
  {
    id: 'gemini',
    label: 'Gemini',
    icon: '✨',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('google-gemini')],
    extraRules: ['DOMAIN-SUFFIX,aistudio.google.com', 'DOMAIN-SUFFIX,notebooklm.google.com'],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 98,
  },
  {
    id: 'grok',
    label: 'Grok',
    icon: '𝕏',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('xai')],
    extraRules: ['DOMAIN-SUFFIX,grok.com'],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 97,
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    icon: '🔎',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('perplexity')],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 96,
  },
  {
    id: 'copilot',
    label: 'GitHub Copilot',
    icon: '🧑‍✈️',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('github-copilot')],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 95,
    optional: true,
  },
  {
    id: 'groq',
    label: 'Groq',
    icon: '⚡',
    module: 'ai',
    category: 'ai',
    ruleProviders: [geosite('groq')],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 94,
    optional: true,
  },
  {
    id: 'meta-ai',
    label: 'Meta AI',
    icon: '♾️',
    module: 'ai',
    category: 'ai',
    ruleProviders: [],
    extraRules: ['DOMAIN-SUFFIX,meta.ai'],
    defaultStrategyCandidates: AI_CANDIDATES,
    priority: 93,
    optional: true,
  },
]
