import type { RuleService } from '@/types'
import { geoip, geosite } from '../ruleProviders'

const SOCIAL_CANDIDATES = ['global:auto', 'regions:auto', 'sources:all', 'global:manual']

export const socialServices: RuleService[] = [
  {
    id: 'telegram',
    label: 'Telegram',
    icon: '✈️',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('telegram'), geoip('telegram')],
    defaultStrategyCandidates: ['region:sg:auto', ...SOCIAL_CANDIDATES],
    priority: 100,
  },
  {
    id: 'twitter',
    label: 'X / Twitter',
    icon: '🐦',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('twitter'), geoip('twitter')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 99,
  },
  {
    id: 'reddit',
    label: 'Reddit',
    icon: '👽',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('reddit')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 98,
  },
  {
    id: 'facebook',
    label: 'Facebook',
    icon: '📘',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('facebook'), geoip('facebook')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 97,
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    icon: '💬',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('whatsapp')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 96,
  },
  {
    id: 'instagram',
    label: 'Instagram',
    icon: '📷',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('instagram')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 95,
    optional: true,
  },
  {
    id: 'discord',
    label: 'Discord',
    icon: '🎙️',
    module: 'social',
    category: 'social',
    ruleProviders: [geosite('discord')],
    defaultStrategyCandidates: SOCIAL_CANDIDATES,
    priority: 94,
    optional: true,
  },
]
