import type { RuleService } from '@/types'
import { geoip, geosite } from '../ruleProviders'

const MEDIA_CANDIDATES = [
  'region:hk:auto',
  'region:tw:auto',
  'region:sg:auto',
  'region:jp:auto',
  'region:us:auto',
  'sources:all',
  'global:auto',
  'global:manual',
]

/** Netflix / Disney+ / HBO libraries are region-bound, so a manual pick is the sensible default. */
const UNLOCK_CANDIDATES = [
  'region:sg:manual',
  'region:hk:manual',
  'region:tw:manual',
  'region:jp:manual',
  'region:us:manual',
  'regions:auto',
  'sources:all',
  'global:manual',
]

export const streamingServices: RuleService[] = [
  {
    id: 'youtube',
    label: 'YouTube',
    icon: '▶️',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('youtube')],
    defaultStrategyCandidates: MEDIA_CANDIDATES,
    priority: 100,
  },
  {
    id: 'netflix',
    label: 'Netflix',
    icon: '🎬',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('netflix'), geoip('netflix')],
    defaultStrategyCandidates: UNLOCK_CANDIDATES,
    priority: 99,
  },
  {
    id: 'disney',
    label: 'Disney+',
    icon: '🏰',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('disney')],
    defaultStrategyCandidates: UNLOCK_CANDIDATES,
    priority: 98,
  },
  {
    id: 'hbo',
    label: 'HBO',
    icon: '📺',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('hbo')],
    defaultStrategyCandidates: UNLOCK_CANDIDATES,
    priority: 97,
  },
  {
    id: 'spotify',
    label: 'Spotify',
    icon: '🎧',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('spotify')],
    defaultStrategyCandidates: MEDIA_CANDIDATES,
    priority: 96,
  },
  {
    id: 'primevideo',
    label: 'Prime Video',
    icon: '📦',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('primevideo')],
    defaultStrategyCandidates: UNLOCK_CANDIDATES,
    priority: 95,
    optional: true,
  },
  {
    id: 'twitch',
    label: 'Twitch',
    icon: '🎮',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('twitch')],
    defaultStrategyCandidates: MEDIA_CANDIDATES,
    priority: 94,
    optional: true,
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    icon: '🎵',
    module: 'streaming',
    category: 'streaming',
    ruleProviders: [geosite('tiktok')],
    defaultStrategyCandidates: UNLOCK_CANDIDATES,
    priority: 93,
    optional: true,
  },
]
